"""Role to permission catalog. Stored in role_permissions and read back at decision time."""

from app.constants import Action, ResourceType, RoleName

_A = Action
_R = ResourceType


def _pairs(*items: tuple[ResourceType, Action]) -> frozenset[tuple[ResourceType, Action]]:
    return frozenset(items)


POLICE_OFFICER_PERMISSIONS = _pairs(
    (_R.CASE, _A.READ),
    (_R.DOCUMENT, _A.CREATE),
    (_R.DOCUMENT, _A.READ),
    (_R.DOCUMENT, _A.UPDATE),
    (_R.DOCUMENT, _A.UPLOAD),
    (_R.DOCUMENT, _A.DOWNLOAD),
    (_R.DOCUMENT, _A.REQUEST_ACCESS),
    (_R.EVIDENCE, _A.READ),
    (_R.EVIDENCE, _A.UPLOAD),
    (_R.EVIDENCE, _A.DOWNLOAD),
    (_R.EVIDENCE, _A.VERIFY),
    (_R.EVIDENCE, _A.REQUEST_ACCESS),
    (_R.DERIVED_ARTIFACT, _A.READ),
    (_R.DERIVED_ARTIFACT, _A.DOWNLOAD),
    (_R.FORENSIC_REPORT, _A.CREATE),
    (_R.FORENSIC_REPORT, _A.READ),
    (_R.REVISION, _A.CREATE),
    (_R.REVISION, _A.READ),
    (_R.REVISION, _A.UPDATE),
    (_R.ACCESS_REQUEST, _A.CREATE),
    (_R.ACCESS_REQUEST, _A.READ),
)

POLICE_SUPERVISOR_PERMISSIONS = _pairs(
    (_R.CASE, _A.READ),
    (_R.CASE, _A.CREATE),
    (_R.CASE, _A.UPDATE),
    (_R.CASE, _A.ASSIGN),
    (_R.DOCUMENT, _A.READ),
    (_R.DOCUMENT, _A.REVIEW),
    (_R.DOCUMENT, _A.APPROVE),
    (_R.DOCUMENT, _A.DOWNLOAD),
    (_R.EVIDENCE, _A.READ),
    (_R.EVIDENCE, _A.DOWNLOAD),
    (_R.EVIDENCE, _A.VERIFY),
    (_R.EVIDENCE, _A.APPROVE),
    (_R.DERIVED_ARTIFACT, _A.READ),
    (_R.DERIVED_ARTIFACT, _A.DOWNLOAD),
    (_R.FORENSIC_REPORT, _A.READ),
    (_R.FORENSIC_REPORT, _A.REVIEW),
    (_R.FORENSIC_REPORT, _A.APPROVE),
    (_R.FORENSIC_REPORT, _A.REJECT),
    (_R.FORENSIC_REPORT, _A.ASSIGN),
    (_R.ACCESS_REQUEST, _A.CREATE),
    (_R.ACCESS_REQUEST, _A.READ),
    (_R.ACCESS_REQUEST, _A.APPROVE),
    (_R.ACCESS_REQUEST, _A.REJECT),
    (_R.REVISION, _A.READ),
    (_R.REVISION, _A.REVIEW),
    (_R.REVISION, _A.APPROVE),
    (_R.REVISION, _A.REJECT),
)

FORENSIC_EXAMINER_PERMISSIONS = _pairs(
    (_R.CASE, _A.READ),
    (_R.EVIDENCE, _A.READ),
    (_R.EVIDENCE, _A.DOWNLOAD),
    (_R.EVIDENCE, _A.VERIFY),
    (_R.EVIDENCE, _A.REQUEST_ACCESS),
    (_R.FORENSIC_REPORT, _A.CREATE),
    (_R.FORENSIC_REPORT, _A.READ),
    (_R.FORENSIC_REPORT, _A.UPDATE),
    (_R.FORENSIC_REPORT, _A.UPLOAD),
    (_R.DERIVED_ARTIFACT, _A.CREATE),
    (_R.DERIVED_ARTIFACT, _A.READ),
    (_R.DERIVED_ARTIFACT, _A.UPLOAD),
    (_R.DERIVED_ARTIFACT, _A.DOWNLOAD),
    (_R.ACCESS_REQUEST, _A.CREATE),
    (_R.ACCESS_REQUEST, _A.READ),
)

FORENSIC_REVIEWER_PERMISSIONS = _pairs(
    (_R.CASE, _A.READ),
    (_R.EVIDENCE, _A.READ),
    (_R.FORENSIC_REPORT, _A.READ),
    (_R.FORENSIC_REPORT, _A.REVIEW),
    (_R.FORENSIC_REPORT, _A.APPROVE),
    (_R.FORENSIC_REPORT, _A.REJECT),
    (_R.DERIVED_ARTIFACT, _A.READ),
    (_R.DERIVED_ARTIFACT, _A.REVIEW),
    (_R.ACCESS_REQUEST, _A.CREATE),
    (_R.ACCESS_REQUEST, _A.READ),
    (_R.ACCESS_REQUEST, _A.APPROVE),
    (_R.ACCESS_REQUEST, _A.REJECT),
)

PROSECUTOR_PERMISSIONS = _pairs(
    (_R.CASE, _A.READ),
    (_R.DOCUMENT, _A.READ),
    (_R.DOCUMENT, _A.CREATE),
    (_R.DOCUMENT, _A.UPLOAD),
    (_R.DOCUMENT, _A.DOWNLOAD),
    (_R.DOCUMENT, _A.REQUEST_ACCESS),
    (_R.EVIDENCE, _A.READ),
    (_R.EVIDENCE, _A.DOWNLOAD),
    (_R.EVIDENCE, _A.REQUEST_ACCESS),
    (_R.DERIVED_ARTIFACT, _A.READ),
    (_R.FORENSIC_REPORT, _A.READ),
    (_R.REVISION, _A.READ),
    (_R.COURT_PACKAGE, _A.READ),
    (_R.COURT_PACKAGE, _A.CREATE),
    (_R.ACCESS_REQUEST, _A.CREATE),
    (_R.ACCESS_REQUEST, _A.READ),
    (_R.ACCESS_REQUEST, _A.APPROVE),
    (_R.ACCESS_REQUEST, _A.REJECT),
)

JUDICIAL_USER_PERMISSIONS = _pairs(
    (_R.CASE, _A.READ),
    (_R.DOCUMENT, _A.READ),
    (_R.DOCUMENT, _A.CREATE),
    (_R.DOCUMENT, _A.UPLOAD),
    (_R.EVIDENCE, _A.READ),
    (_R.EVIDENCE, _A.VERIFY),
    (_R.DERIVED_ARTIFACT, _A.READ),
    (_R.FORENSIC_REPORT, _A.READ),
    (_R.FORENSIC_REPORT, _A.VERIFY),
    (_R.REVISION, _A.READ),
    (_R.COURT_PACKAGE, _A.READ),
    (_R.COURT_PACKAGE, _A.VERIFY),
    (_R.ACCESS_REQUEST, _A.CREATE),
    (_R.ACCESS_REQUEST, _A.READ),
    (_R.ACCESS_REQUEST, _A.APPROVE),
    (_R.ACCESS_REQUEST, _A.REJECT),
)

ADMIN_PERMISSIONS = _pairs(
    (_R.USER, _A.CREATE),
    (_R.USER, _A.READ),
    (_R.USER, _A.UPDATE),
    (_R.ROLE, _A.READ),
    (_R.ROLE, _A.UPDATE),
    (_R.DEPARTMENT, _A.READ),
    (_R.AUDIT_LOG, _A.READ),
)

ROLE_PERMISSIONS: dict[str, frozenset[tuple[ResourceType, Action]]] = {
    RoleName.ADMIN.value: ADMIN_PERMISSIONS,
    RoleName.POLICE_OFFICER.value: POLICE_OFFICER_PERMISSIONS,
    RoleName.POLICE_SUPERVISOR.value: POLICE_SUPERVISOR_PERMISSIONS,
    RoleName.FORENSIC_EXAMINER.value: FORENSIC_EXAMINER_PERMISSIONS,
    RoleName.FORENSIC_REVIEWER.value: FORENSIC_REVIEWER_PERMISSIONS,
    RoleName.PROSECUTOR.value: PROSECUTOR_PERMISSIONS,
    RoleName.JUDICIAL_USER.value: JUDICIAL_USER_PERMISSIONS,
}
