"""Shared domain values used by models, schemas, and services."""

from enum import Enum


class RoleName(str, Enum):
    ADMIN = "ADMIN"
    POLICE_OFFICER = "POLICE_OFFICER"
    POLICE_SUPERVISOR = "POLICE_SUPERVISOR"
    FORENSIC_EXAMINER = "FORENSIC_EXAMINER"
    FORENSIC_REVIEWER = "FORENSIC_REVIEWER"
    PROSECUTOR = "PROSECUTOR"
    JUDICIAL_USER = "JUDICIAL_USER"


class CaseType(str, Enum):
    CRIMINAL = "CRIMINAL"
    CIVIL = "CIVIL"
    FORENSIC = "FORENSIC"
    ADMINISTRATIVE = "ADMINISTRATIVE"


class CaseStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    UNDER_INVESTIGATION = "UNDER_INVESTIGATION"
    UNDER_REVIEW = "UNDER_REVIEW"
    READY_FOR_PROSECUTION = "READY_FOR_PROSECUTION"
    IN_COURT = "IN_COURT"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class CaseEventType(str, Enum):
    CASE_CREATED = "CASE_CREATED"
    ASSIGNMENT_ADDED = "ASSIGNMENT_ADDED"
    ASSIGNMENT_REMOVED = "ASSIGNMENT_REMOVED"
    STATUS_CHANGED = "STATUS_CHANGED"
    DOCUMENT_REVISION_CREATED = "DOCUMENT_REVISION_CREATED"
    DOCUMENT_REVISION_SUBMITTED = "DOCUMENT_REVISION_SUBMITTED"
    DOCUMENT_REVISION_APPROVED = "DOCUMENT_REVISION_APPROVED"
    DOCUMENT_REVISION_REJECTED = "DOCUMENT_REVISION_REJECTED"
    DOCUMENT_VERSION_DOWNLOADED = "DOCUMENT_VERSION_DOWNLOADED"
    DOCUMENT_VERSION_VIEWED = "DOCUMENT_VERSION_VIEWED"
    SEARCH_PERFORMED = "SEARCH_PERFORMED"
    DOCUMENT_SEARCH_RESULT_OPENED = "DOCUMENT_SEARCH_RESULT_OPENED"
    RAG_QUERY_EXECUTED = "RAG_QUERY_EXECUTED"


class ExtractionMethod(str, Enum):
    TEXT_EXTRACTION = "TEXT_EXTRACTION"
    OCR = "OCR"


class ExtractionStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class IndexStatus(str, Enum):
    PENDING = "PENDING"
    READY = "READY"
    FAILED = "FAILED"


class SearchMode(str, Enum):
    LEXICAL = "lexical"
    SEMANTIC = "semantic"
    HYBRID = "hybrid"


class MatchType(str, Enum):
    LEXICAL = "LEXICAL"
    SEMANTIC = "SEMANTIC"
    HYBRID = "HYBRID"
    METADATA = "METADATA"


class AssignmentType(str, Enum):
    PRIMARY_OFFICER = "PRIMARY_OFFICER"
    SUPERVISOR = "SUPERVISOR"
    FORENSIC_EXAMINER = "FORENSIC_EXAMINER"
    FORENSIC_REVIEWER = "FORENSIC_REVIEWER"
    PROSECUTOR = "PROSECUTOR"
    JUDICIAL_ACCESS = "JUDICIAL_ACCESS"


class Classification(str, Enum):
    UNCLASSIFIED = "UNCLASSIFIED"
    RESTRICTED = "RESTRICTED"
    CONFIDENTIAL = "CONFIDENTIAL"


class DocumentType(str, Enum):
    FIR = "FIR"
    POLICE_REPORT = "POLICE_REPORT"
    INVESTIGATION_RECORD = "INVESTIGATION_RECORD"
    WITNESS_STATEMENT = "WITNESS_STATEMENT"
    CHARGE_SHEET = "CHARGE_SHEET"
    COURT_FILING = "COURT_FILING"
    EVIDENCE_RECORD = "EVIDENCE_RECORD"
    FORENSIC_REPORT = "FORENSIC_REPORT"
    LEGAL_NOTICE = "LEGAL_NOTICE"
    PROSECUTION_SUBMISSION = "PROSECUTION_SUBMISSION"
    JUDGMENT = "JUDGMENT"
    COURT_ORDER = "COURT_ORDER"
    PROCEEDINGS = "PROCEEDINGS"
    CASE_DIARY = "CASE_DIARY"


class DocumentClassification(str, Enum):
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    HIGHLY_CONFIDENTIAL = "HIGHLY_CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class DocumentVersionStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED_FOR_REVIEW = "SUBMITTED_FOR_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class VersionReviewDecision(str, Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"


class DocumentStatus(str, Enum):
    DRAFT = "DRAFT"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    SEALED = "SEALED"
    ARCHIVED = "ARCHIVED"


class EvidenceType(str, Enum):
    CCTV_VIDEO = "CCTV_VIDEO"
    AUDIO_RECORDING = "AUDIO_RECORDING"
    PHOTOGRAPH = "PHOTOGRAPH"
    MOBILE_DUMP = "MOBILE_DUMP"
    DISK_IMAGE = "DISK_IMAGE"
    DOCUMENT = "DOCUMENT"
    SCREENSHOT = "SCREENSHOT"
    DIGITAL_FILE = "DIGITAL_FILE"
    FORENSIC_IMAGE = "FORENSIC_IMAGE"
    OTHER = "OTHER"


class EvidenceStatus(str, Enum):
    RECEIVED = "RECEIVED"
    VERIFIED = "VERIFIED"
    SEALED = "SEALED"
    ARCHIVED = "ARCHIVED"


class ArtifactType(str, Enum):
    VIDEO_CLIP = "VIDEO_CLIP"
    IMAGE_CROP = "IMAGE_CROP"
    ENHANCED_IMAGE = "ENHANCED_IMAGE"
    AUDIO_EXTRACTION = "AUDIO_EXTRACTION"
    CONVERTED_FILE = "CONVERTED_FILE"
    SCREENSHOT = "SCREENSHOT"
    TEXT_EXTRACTION = "TEXT_EXTRACTION"
    ANNOTATION = "ANNOTATION"
    FORENSIC_OUTPUT = "FORENSIC_OUTPUT"
    OTHER = "OTHER"


class ArtifactStatus(str, Enum):
    RECORDED = "RECORDED"


class IntegrityStatus(str, Enum):
    VERIFIED = "VERIFIED"
    INTEGRITY_MISMATCH = "INTEGRITY_MISMATCH"


class ForensicRequestType(str, Enum):
    DIGITAL_FORENSICS = "DIGITAL_FORENSICS"
    VIDEO_ANALYSIS = "VIDEO_ANALYSIS"
    IMAGE_ANALYSIS = "IMAGE_ANALYSIS"
    AUDIO_ANALYSIS = "AUDIO_ANALYSIS"
    MOBILE_FORENSICS = "MOBILE_FORENSICS"
    DISK_FORENSICS = "DISK_FORENSICS"
    DOCUMENT_FORENSICS = "DOCUMENT_FORENSICS"
    OTHER = "OTHER"


class ForensicRequestStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED_FOR_REVIEW = "SUBMITTED_FOR_REVIEW"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class FindingType(str, Enum):
    OBSERVATION = "OBSERVATION"
    IDENTIFICATION = "IDENTIFICATION"
    CORRELATION = "CORRELATION"
    ANOMALY = "ANOMALY"
    TECHNICAL_FINDING = "TECHNICAL_FINDING"
    OTHER = "OTHER"


class FindingStatus(str, Enum):
    RECORDED = "RECORDED"
    ACCEPTED = "ACCEPTED"


class ReviewDecision(str, Enum):
    ACCEPT = "ACCEPT"
    RETURN = "RETURN"


class CustodyEventType(str, Enum):
    EVIDENCE_UPLOADED = "EVIDENCE_UPLOADED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    EVIDENCE_ACCESSED = "EVIDENCE_ACCESSED"
    EVIDENCE_DOWNLOADED = "EVIDENCE_DOWNLOADED"
    FORENSIC_REQUEST_CREATED = "FORENSIC_REQUEST_CREATED"
    FORENSIC_REQUEST_APPROVED = "FORENSIC_REQUEST_APPROVED"
    FORENSIC_REQUEST_ASSIGNED = "FORENSIC_REQUEST_ASSIGNED"
    FORENSIC_ANALYSIS_STARTED = "FORENSIC_ANALYSIS_STARTED"
    DERIVED_ARTIFACT_CREATED = "DERIVED_ARTIFACT_CREATED"
    FORENSIC_REVIEW_SUBMITTED = "FORENSIC_REVIEW_SUBMITTED"
    FORENSIC_REVIEW_ACCEPTED = "FORENSIC_REVIEW_ACCEPTED"
    FORENSIC_REVIEW_RETURNED = "FORENSIC_REVIEW_RETURNED"
    EVIDENCE_SEALED = "EVIDENCE_SEALED"
    EVIDENCE_TRANSFERRED = "EVIDENCE_TRANSFERRED"


class RequestStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"


class ResourceType(str, Enum):
    CASE = "CASE"
    DOCUMENT = "DOCUMENT"
    EVIDENCE = "EVIDENCE"
    FORENSIC_REPORT = "FORENSIC_REPORT"
    DERIVED_ARTIFACT = "DERIVED_ARTIFACT"
    REVISION = "REVISION"
    ACCESS_REQUEST = "ACCESS_REQUEST"
    COURT_PACKAGE = "COURT_PACKAGE"
    AUDIT_LOG = "AUDIT_LOG"
    USER = "USER"
    ROLE = "ROLE"
    DEPARTMENT = "DEPARTMENT"


class Action(str, Enum):
    CREATE = "CREATE"
    READ = "READ"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    UPLOAD = "UPLOAD"
    DOWNLOAD = "DOWNLOAD"
    REQUEST_ACCESS = "REQUEST_ACCESS"
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REVIEW = "REVIEW"
    VERIFY = "VERIFY"
    SIGN = "SIGN"
    ASSIGN = "ASSIGN"
    EXPORT = "EXPORT"


class DecisionReason(str, Enum):
    ALLOW = "ALLOW"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    USER_INACTIVE = "USER_INACTIVE"
    INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE"
    MISSING_PERMISSION = "MISSING_PERMISSION"
    CASE_ACCESS_DENIED = "CASE_ACCESS_DENIED"
    RESOURCE_ACCESS_DENIED = "RESOURCE_ACCESS_DENIED"
    DEPARTMENT_RESTRICTION = "DEPARTMENT_RESTRICTION"
    INVALID_RESOURCE = "INVALID_RESOURCE"
    ACTION_NOT_ALLOWED = "ACTION_NOT_ALLOWED"
